---
output:
  html_document: default
  pdf_document: default
---
#泰坦尼克
titanic<-read.csv(file.choose())

summary(titanic)#population
head(titanic)#top 6


titanic$Pclass <- factor(titanic$Pclass)#因子类型定义，分类变量

sum(is.na(titanic$Age))
sum(is.na(titanic$Cabin))
summary(titanic$Cabin)

library(colorspace)
library(grid)
library(data.table)
library(VIM)
library(mice)
library(ggplot2)
NaPlot <- aggr(titanic,
               col=c("cyan", "red"), 
               numbers=TRUE, 
               labels=names(data), 
               cex.axis=.7, 
               gap=3, 
               ylab=c("Histogram  of missing data","Pattern")) #缺失值信息可视化


median(titanic$Age,na.rm = T)
titanic$Age[is.na(titanic$Age)] <- median(titanic$Age,na.rm = T)
titanic$Embarked[is.na(titanic$Embarked)] <- 'S'
summary(titanic)


library(lattice)
library(caret) #版本不够
base <- data.frame(predict(dummyVars(~., data = titanic), titanic))
trainid <- createDataPartition(base$PassengerId, p = 0.75, list = F)
 train <- base[trainid,]
 test <- base[-trainid,]#方法错误
 #直接读取，全样本作为测试集（准确率偏高一些）
 train<-read.csv(file.choose())
 test<-read.csv(file.choose())
 

library(ggplot2) 
Pclass_S <- table(train$Survived, train$Pclass) 
Pclass_S_prop <- prop.table(Pclass_S, 2) 
ggplot(data = train, aes(x = Pclass, fill = factor(Survived)))+geom_bar(stat='count', position='dodge') + scale_x_continuous(breaks=c(1:3)) + labs(x = 'Pclass')

Pclass_S_prop


Sex_S <- table(train$Survived, train$Sex)
Sex_S_prop <- prop.table(Sex_S, 2)
ggplot(data = train, aes(x = Sex, fill = factor(Survived)))+geom_bar(stat='count', position='dodge')


Agedata <- as.numeric(unlist(train$Age))
Age_Level<-cut(Agedata, breaks = c(0, 15, 30, 45, 60, 75, 90), labels = c('kids', 'teenagers', 'prime', 'middle', 'agedness', 'senium' ))
Age_S <- table(train$Survived, Age_Level)
Age_S_prop <- prop.table(Age_S, 2)
ggplot(data = data.frame(train$Survived, Agedata), aes(x = cut(Agedata, breaks = c(0, 15, 30, 45, 60, 75, 90)), fill = factor(train.Survived)))+geom_bar(stat='count', position='dodge') + labs(x = 'Age') +  scale_x_discrete(labels = c('kids', 'teenagers', 'prime', 'middle', 'agedness', 'senium'))


Sibsp_S <- table(train$Survived, train$SibSp)
Parch_S <- table(train$Survived, train$Parch)
Sibsp_S_prop <- prop.table(Sibsp_S, 2)
Parch_S_prop <- prop.table(Parch_S, 2)
ggplot(data = train, aes(x = SibSp, fill = factor(Survived)))+geom_bar(stat='count', position='dodge') + scale_x_continuous(breaks=c(0:8)) + labs(x = 'Sibsp')
ggplot(data = train, aes(x = Parch, fill = factor(Survived)))+geom_bar(stat='count', position='dodge') + scale_x_continuous(breaks=c(0:6)) + labs(x = 'Parch')
Families <- train$SibSp +train$Parch
ggplot(data = train, aes(x = Families, fill = factor(Survived)))+geom_bar(stat='count', position='dodge') + scale_x_continuous(breaks=c(0:10)) + labs(x = 'Families')



Faredata <- as.numeric(unlist(train$Fare))
Fare_S <- table(train$Survived, cut(Faredata, breaks = c(0, 50, 100, 600), labels = c('poor', 'middle', 'rich')))
Fare_S_prop <- prop.table(Fare_S, 2)
ggplot(data = data.frame(train$Survived, Faredata), aes(x = cut(Faredata, breaks = c(0, 50, 100, 600)), fill = factor(train.Survived)))+geom_bar(stat='count', position='dodge') + labs(x = 'Fare') +  scale_x_discrete(labels = c('poor', 'middle', 'rich'))
Embarked_S <- table(train$Survived, train$Embarked)
Embarked_S_prop <- prop.table(Embarked_S, 2)
ggplot(data = train, aes(x = Embarked, fill = factor(Survived)))+geom_bar(stat='count', position='dodge')



library(dplyr)
library(stringr)
library(colorspace)
library(grid)
library(data.table)
library(VIM)
library(mice)
library(ggplot2)
library(lattice)
library(caret) #版本不够

base <- data.frame(predict(dummyVars(~., data = titanic), titanic))

logistic <- glm(Survived ~Pclass+Sex+Age+SibSp+Parch+Fare,data = train[, -1],family = 'binomial'(link = 'logit'))
summary(logistic)

library(randomForest)
library(ggplot2)
set.seed(123)
RF <- randomForest(factor(base$Survived) ~ ., data = base, importance = TRUE)

RF_tree <- plot(RF)
tree <- c(1:500)
OOB <- data.frame(tree, RF_tree)
ggplot(data = OOB, aes(x = tree))+geom_line(aes(y = OOB), colour = "black", size = 0.8)+geom_line(aes(y = X0), colour = "red", size = 0.8)+geom_line(aes(y = X1), colour = "green", size = 0.8) + labs(y = "Error.rate") + theme_bw()


test<-read.csv(file.choose())#test datsets,test3

test$predict <- predict(logistic, test, type='response')
test$predictClass <- NULL
test$predictClass[test$predict >= 0.5] <- 1 #逻辑回归得到的是一个概率值，而如何去划分需要我们指定，本例中大于等于0.5为正例，即：幸存。0.5也可以划分为0，已经测试过这个例子中不影响预测结
test$predictClass[test$predict < 0.5] <- 0
test$predictClass[is.na(test$predict)] <- 0
table(test$Survived, test$predictClass)

#钻石
library(ggplot2)
require(ggplot2)
data()
data(diamonds)
head(diamonds)

hist(diamonds$carat,main="Carat Histogram",xlab="Carat")

plot(price~carat,data=diamonds)
plot(log(price)~log(carat),data=diamonds)
ggplot(diamonds,aes(x=carat,y=price))+geom_point()

ggplot(diamonds,aes(x=carat,y=price))+geom_point(aes(color=color))
ggplot(diamonds,aes(x=carat,y=price))+geom_point(aes(color=color))+facet_grid(cut~clarity)

library(ggthemes)
ggplot(diamonds,aes(x=carat,y=price))+geom_point(aes(color=color))+theme_wsj()

